#! /bin/sh

plannerclient --host=localhost --port=2323 --client-name=team-1-fsp-rbh --planner=complete --algorithm=fsp-star --encoding=graph --heuristic=relaxed-bounds --epsilon=0.01 --discount-factor=0.8 $@
